<h1>服务列表</h1>
<a class="btn btn-default" href="#" role="button">添加服务</a>
<div class="table-responsive">
  <table class="table table-bordered  table-hover">
  	<theader>
  		<tr>
	    	<td>id</td>
	    	<td>服务名称</td>
	    	<td>服务说明</td>
	    	<td>服务类型</td>
	    	<td>是否含有开放接口</td>
	    	<td>是否是内部服务</td>
	    	<td>创建时间</td>
	    	<td>状态</td>
	    	<td>服务操作</td>
    	</tr>

  	</theader>

    	
    <tbody>
    	<?php foreach($services as $v ){?>
    		<tr>
    			<td><?= $v->id ?></td>
    			<td><a href="<?= $v->url ?>"><?= $v->name ?></a></td>
    			<td><?= $v->desc ?></td>
    			<td><?= $config->service_type[$v->type]?:'错误类型' ?></td>
    			<td><?= $v->has_open_api?"是":"否" ?></td>
    			<td><?= $v->is_inside?"是":"否" ?></td>
    			<td><?= $v->created_at ?></td>
    			<td><p class="<?= $v->status == 1?"text-success":"text_warning" ?>"><?= $v->status == 1?"使用中":"停用" ?></p></td>
	    		<td><a href="/services/delete" class="btn btn-link">停用</a></td>
    		</tr>
    	<?php }?>
    </tbody>
    	

  </table>
</div>