<h1>服务添加</h1>

<form class="form-horizontal" action="/services-add" method="post">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">服务名称</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" name="name" >
    </div>
  </div>

 


  <div class="form-group">
    <label for="url" class="col-sm-2 control-label">路由链接</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="url" name="url" placeholder="例如: /Wechat">
    </div>
  </div>

  <div class="form-group">
    <label for="type" class="col-sm-2 control-label">路由类型</label>
    <div class="col-sm-10">
      <div class="radio">
        <label>
          <input type="radio" name="type"  value="1" checked>
            系统服务
        </label>
      </div>
      <div class="radio">
        <label>
          <input type="radio" name="type"  value="2">
            api管理
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label for="type" class="col-sm-2 control-label">是否有开放api</label>
    <div class="col-sm-10">
      <div class="radio">
        <label>
          <input type="radio" name="has_open_api"  value="1" checked>
            有
        </label>
      </div>
      <div class="radio">
        <label>
          <input type="radio" name="has_open_api"  value="0">
            无
        </label>
      </div>
    </div>
  </div>
  <!-- <div class="form-group">
    <label for="router_desc" class="col-sm-2 control-label">说明</label>
    <div class="col-sm-10">
      <textarea class="form-control"  name = 'router_desc' rows="3"></textarea>
    </div>
  </div> -->

  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>
</form>