<h1>路由添加</h1>

<form class="form-horizontal" action="/router-update" method="post">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">接口名称</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" name="name" value="<?= $router->name ?>" >
    </div>
  </div>

  <div class="form-group">
    <label for="controllers" class="col-sm-2 control-label">控制器</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="controllers" name="controllers" value="<?= $router->controllers ?>">
  </div>

  </div>
  <div class="form-group">
    <label for="action" class="col-sm-2 control-label">方法名</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="action" name="action" value="<?= $router->action ?>" >
    </div>
  </div>



  <div class="form-group">
    <label for="url" class="col-sm-2 control-label">路由链接</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="url" name="url" value="<?= $router->url ?>">
    </div>
  </div>

  <div class="form-group">
    <label for="type" class="col-sm-2 control-label">路由类型</label>
    <div class="col-sm-10">
      <div class="radio">
        <label>
          <input type="radio" name="type"  value="api" <?= $router->type =='api'?"checked":'' ?> >
            接口
        </label>
      </div>
      <div class="radio">
        <label>
          <input type="radio" name="type"  value="web" <?= $router->type =='web'?"checked":'' ?> >
            页面
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label for="router_desc" class="col-sm-2 control-label">说明</label>
    <div class="col-sm-10">
      <textarea class="form-control"  name='router_desc' rows="3" ><?= $router->router_desc ?> </textarea>
    </div>
  </div>

  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input type="hidden" name="id" value="<?=$router->id?>">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>
</form>