<h1>路由添加</h1>

<form class="form-horizontal" action="/router-add" method="post">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">接口名称</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" name="name" >
    </div>
  </div>

  <div class="form-group">
    <label for="controllers" class="col-sm-2 control-label">控制器</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="controllers" name="controllers" placeholder="例如: Index">
  </div>

  </div>
  <div class="form-group">
    <label for="action" class="col-sm-2 control-label">方法名</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="action" name="action" placeholder="例如: index">
    </div>
  </div>



  <div class="form-group">
    <label for="url" class="col-sm-2 control-label">路由链接</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="url" name="url" placeholder="例如: index/index">
    </div>
  </div>

  <div class="form-group">
    <label for="type" class="col-sm-2 control-label">路由类型</label>
    <div class="col-sm-10">
      <div class="radio">
        <label>
          <input type="radio" name="type"  value="api" checked>
            接口
        </label>
      </div>
      <div class="radio">
        <label>
          <input type="radio" name="type"  value="web">
            页面
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label for="desc" class="col-sm-2 control-label">说明</label>
    <div class="col-sm-10">
      <textarea class="form-control" rows="3"></textarea>
    </div>
  </div>

  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>
</form>