<h1>公众号添加</h1>

<form class="form-horizontal" action="/wechat-add" method="post" enctype="multipart/form-data">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">公众号名称</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" name="name" >
    </div>
  </div>

  <div class="form-group">
    <label for="username" class="col-sm-2 control-label">账号</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="username" name="username" >
  </div>

  </div>
  <div class="form-group">
    <label for="password" class="col-sm-2 control-label">密码</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="password" name="password" >
    </div>
  </div>



  <div class="form-group">
    <label for="pm_name" class="col-sm-2 control-label">管理员联系人</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="pm_name" name="pm_name">
    </div>
  </div>


  <div class="form-group">
    <label for="pm_tel" class="col-sm-2 control-label">管理员联系方式</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="pm_tel" name="pm_tel">
    </div>
  </div>


  <div class="form-group">
    <label for="app_id" class="col-sm-2 control-label">appid</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="app_id" name="app_id">
    </div>
  </div>


  <div class="form-group">
    <label for="app_secret" class="col-sm-2 control-label">appsecret</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="app_secret" name="app_secret">
    </div>
  </div>


  <div class="form-group">
    <label for="check_file" class="col-sm-2 control-label">服务器认证文件</label>
    <div class="col-sm-10">
      <input type="file" class="form-control" id="check_file" name="check_file">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>
</form>